services:
  dbbkp-postgres:
    image: postgres:15-alpine
    container_name: dbbkp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: dbbkp_panel
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  dbbkp-redis:
    image: redis:7-alpine
    container_name: dbbkp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  dbbkp-redis-ui:
    image: rediscommander/redis-commander
    container_name: dbbkp-redis-ui
    environment:
      - REDIS_HOSTS=local:dbbkp-redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - dbbkp-redis
